External support review
M-AminAlizadeh/Booking-doctor-appointment-front-end pull request #18
Opened 2023-12-20 13:20 UTC by M-AminAlizadeh

<html><body>
<h3 tabindex="-1" dir="auto">General requirements</h3>
<ul dir="auto">
<li>Make sure that there are <a href="https://github.com/microverseinc/linters-config">no linter errors</a>.</li>
<li>Make sure that you used correct <a href="https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md">Gitflow</a>.</li>
<li>Make sure that you documented your work <a href="https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md">in a professional way</a>.</li>
</ul>
<h3 tabindex="-1" dir="auto"><a id="user-content-htmlcss-javascript-and-ruby-requirements" class="anchor" aria-hidden="true" tabindex="-1" href="https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md#htmlcss-javascript-and-ruby-requirements"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"></svg></a></h3><h3 tabindex="-1" dir="auto">HTML/CSS, JavaScript, and Ruby requirements</h3>
<ul dir="auto">
<li>Follow our list of <a href="https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md">best practices for HTML &amp; CSS</a>.</li>
<li>Follow our list of <a href="https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md">best practices for JavaScript</a>.</li>
<li>Follow our list of <a href="https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md">best practices for Ruby</a>.</li>
</ul>
<h3 tabindex="-1" dir="auto"><a id="user-content-project-requirements" class="anchor" aria-hidden="true" tabindex="-1" href="https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md#project-requirements"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"></svg></a></h3><h3 tabindex="-1" dir="auto">Project requirements</h3>
<h4 tabindex="-1" dir="auto"><a id="user-content-basics" class="anchor" aria-hidden="true" tabindex="-1" href="https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md#basics"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"></svg></a></h4><h4 tabindex="-1" dir="auto">Basics</h4>
<ul dir="auto">
<li>You should follow the layout of <a href="https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign" rel="nofollow">the provided design</a>.
 You should change only the titles, descriptions, and photos - in order 
to create a website about something other than motorcycles.</li>
<li>Select a theme for your website - is it going to be a website for 
booking doctor appointments, booking online classes, or something else?</li>
</ul>
<h4 tabindex="-1" dir="auto"><a id="user-content-features" class="anchor" aria-hidden="true" tabindex="-1" href="https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md#features"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"></svg></a></h4><h4 tabindex="-1" dir="auto">Features</h4>
<p dir="auto">Depending on your team size you are required to complete a
 set number of features. Take inventory of your team and see where you 
fit in the following table:</p>

Team size | # of required features
-- | --
1-2 | 6
3-4 | 9
5 | 11

<p dir="auto">If your team has finished the required features, but you'd
 still like to complete more you are free to continue with the optional 
ones.</p>
<p dir="auto"><strong>Note: If your team decides to implement optional 
features, make sure they work as expected (just like the required ones).
 This will be considered in your final evaluation!</strong></p>
<h5 tabindex="-1" dir="auto"><a id="user-content-core-features---required-for-every-team-size" class="anchor" aria-hidden="true" tabindex="-1" href="https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md#core-features---required-for-every-team-size"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"></svg></a></h5><h5 tabindex="-1" dir="auto">Core features - Required for <em>every</em> team size</h5>
<ol dir="auto">
<li>The user logs in to the website, only by typing the username (a 
proper authenticated login is a requirement if your group is made of 5 
people).</li>
<li>In the navigation panel, the user can see links to:
<ul dir="auto">
<li>Motorcycles/doctors/classes/items that you selected as a theme.</li>
<li>"Reserve" form.</li>
<li>"My reservations".</li>
<li>"Add motorcycle/doctor/class/item that you selected as a theme" (the link is visible to everybody).</li>
<li>"Delete motorcycle/doctor/class/item that you selected as a theme" (the link is visible to everybody).</li>
</ul>
</li>
<li>On the main page, the user can see a <a href="https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005577" rel="nofollow">list of motorcycles/doctors/classes/items that you selected as a theme</a>.</li>
</ol>
<p align="center" dir="auto">
  <a target="_blank" rel="noopener noreferrer" href="https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/images/list.png"><img src="https://github.com/microverseinc/curriculum-final-capstone/raw/main/projects/images/list.png" alt="List" width="300px" style="max-width: 100%;"></a>
</p>
4. When the user selects a specific item, they can see the [details page](<a href="https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005579" rel="nofollow">https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005579</a>) with its full description (skip the "Rotate image" button).
<ul dir="auto">
<li>In the details page, the user can click the "Reserve" button (in the
 design you can see the "Configure" button - please replace it with the 
"Reserve" button).</li>
</ul>
   <p align="center" dir="auto">
     <a target="_blank" rel="noopener noreferrer" href="https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/images/details.png"><img src="https://github.com/microverseinc/curriculum-final-capstone/raw/main/projects/images/details.png" alt="Details" width="300px" style="max-width: 100%;"></a>
   </p>
<ol start="5" dir="auto">
<li>
<p dir="auto">When the user clicks the "Add item" link in the navigation panel they can see a form for adding a new item.</p>
</li>
<li>
<p dir="auto">Make the app responsive, creating both mobile and desktop versions.</p>
</li>
</ol>
<h5 tabindex="-1" dir="auto"><a id="user-content-additional-features---required-for-teams-with-3-4--5-members-optional-for-others" class="anchor" aria-hidden="true" tabindex="-1" href="https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md#additional-features---required-for-teams-with-3-4--5-members-optional-for-others"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"></svg></a></h5><h5 tabindex="-1" dir="auto">Additional features - Required for teams with 3-4 &amp; 5 members (optional for others)</h5>
<ol start="7" dir="auto">
<li>When the user clicks the "Delete item" link in the navigation panel 
they can see a list of all items with title and "Delete" button.
<ul dir="auto">
<li>When the user clicks the "Delete" button, the selected item is marked as removed and does not show on the main list anymore.</li>
</ul>
</li>
</ol>
<ul dir="auto">
<li>To reserve an appointment, the user has to select a date and city (username and selected item are autofilled).
<ul dir="auto">
<li>Use the design based on the <a href="https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005583" rel="nofollow">"Book a vespa test-ride"</a> a [...]

2023-12-20 19:29 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!










#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-12-20 19:29 UTC, Meltrust commented on README.md
> +# 📗 Table of Contents
Thank you for pointing out that the live demo is not working well.  However, the whole frontend app is set to consume the cloud API at onrender.com

- [ ] Since the cloud API at onrender.com is not working, kindly set the frontend project to consume the localhost instead.   You'll need to change all the `onrender` URLs to localhost.

- [ ] Ensure all the setup instructions like how to setup the database, along any special procedures your project may have, like setting up jwt, .env, master.key etc. are included on your readme.

- [ ] After the last change, double-check the cors.rb file is allowing the requests.  Please test the requests work correctly before re-submitting for review.

- [ ] If the live demo does not work, please remove it from your readme until it works.

_note:  A live demo was not a requirement for this project.  We review locally.  Therefore, it is safe to skip the live demo while you are debugging it._

_note 2:  Since the frontend project is full of request URLs to the non-functioning onrender, I didn't access the app.  The main app functionality will be reviewed in the next review._

_note 3:  In summary, just make the frontend app consume the local server and if it works well, that's all you need for now.  You can always add the live demo and the cloud API later when it works._

_note 4:  I strongly suggest against sending the project in this state to final evaluation.  Just make it work locally by updating all the URLs and possibly the cors file._

2023-12-21 12:02 UTC, Meltrust requested changes
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  The app is now accessible through local dev ✔️ 


#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-12-21 12:40 UTC, M-AminAlizadeh commented on src/App.js
> +function App() {
@Meltrust Thank you for the transparent CR

But according to the requirements add/remove items with authority is for groups with 5 members (we are 4)

![Screenshot 2023-12-21 155723](https://github.com/M-AminAlizadeh/Booking-doctor-appointment-front-end/assets/67329484/2df08516-a48d-479c-af4d-2dcf88a79829)

Plus adding/removing items (in this project doctor) by users (patients) is against reality (the patients can not manipulate the doctors only the Admin can and the admin authority is only for groups who are 5)

if I'm wrong, please explain it for me

Thanks

2023-12-21 15:49 UTC, enniopo commented
Hi @M-AminAlizadeh and All, 

This is an additional review as a result of the second opinion request.

The suggestions provided by Miguel (Meltrust) are correct. They align with points #5 (Add) and #7 (Delete)of the project requirements. 

![image](https://github.com/M-AminAlizadeh/Booking-doctor-appointment-front-end/assets/91873608/ef1ad1cd-6048-4c9b-8a7e-9b1b855d4c2a)

What is requested only for a team of 5 members is to implement proper user authentication from the front-end to the server and make sure that the "Add item" and "Delete item" links are accessible only by users who are admins.

Finally, please remember that code reviews for the Final Capstone are all optional, and students can decide whether to follow the suggestions or not.

Thank you
Ennio

2023-12-21 21:21 UTC, Meltrust approved these changes
# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight

- Add and remove doctors feature has been implemented✔️ 
- Superb, beautiful job ✔️  

 ### As an additional note, I'd like to congratulate the team for this effort.  Not only you actually implemented all the features, but you also did it beautifully and in a record time.  

### You are great warriors.  

### I'll see you in the software industry. 💪   

------

2023-12-21 21:21 UTC, Meltrust commented on README.md
> +# 📗 Table of Contents
- [ ] OPTIONAL: You have implemented the add/delete features.  Congratulations! This is great!  

I highly suggest you state on your readme the fact that normal users aren't able to add and delete doctors, only admins.  



That way, your users will able to test the admin feature right away without having to dig into the code. 💪

2024-01-12 19:44 UTC, merged